# Generated by Django 2.2.5 on 2019-10-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('adm', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_inpatient',
            },
        ),
    ]
